# Form implementation generated from reading ui file 'QLNV.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from manager import Manager
from employee import Employee
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QLNV(object):
    def __init__(self, manager : Manager) -> None:
        self.manager = manager

    def setupUi(self, QLNV):
        QLNV.setObjectName("QLNV")
        QLNV.resize(703, 479)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=QLNV)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 684, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Status = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Status.sizePolicy().hasHeightForWidth())
        self.Status.setSizePolicy(sizePolicy)
        self.Status.setObjectName("Status")
        self.gridLayout.addWidget(self.Status, 5, 1, 1, 1)
        self.TenNV = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TenNV.sizePolicy().hasHeightForWidth())
        self.TenNV.setSizePolicy(sizePolicy)
        self.TenNV.setInputMask("")
        self.TenNV.setText("")
        self.TenNV.setObjectName("TenNV")
        self.gridLayout.addWidget(self.TenNV, 1, 1, 1, 2)
        self.LuongNV = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LuongNV.sizePolicy().hasHeightForWidth())
        self.LuongNV.setSizePolicy(sizePolicy)
        self.LuongNV.setText("")
        self.LuongNV.setObjectName("LuongNV")
        self.gridLayout.addWidget(self.LuongNV, 1, 3, 1, 1)
        self.ThemNV = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThemNV.sizePolicy().hasHeightForWidth())
        self.ThemNV.setSizePolicy(sizePolicy)
        self.ThemNV.setObjectName("ThemNV")
        self.gridLayout.addWidget(self.ThemNV, 1, 5, 1, 1)
        self.XoaNV = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XoaNV.sizePolicy().hasHeightForWidth())
        self.XoaNV.setSizePolicy(sizePolicy)
        self.XoaNV.setObjectName("XoaNV")
        self.gridLayout.addWidget(self.XoaNV, 3, 5, 1, 1)
        self.ThongTinNV = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThongTinNV.sizePolicy().hasHeightForWidth())
        self.ThongTinNV.setSizePolicy(sizePolicy)
        self.ThongTinNV.setObjectName("ThongTinNV")
        self.gridLayout.addWidget(self.ThongTinNV, 3, 3, 1, 2)
        self.IDNV = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IDNV.sizePolicy().hasHeightForWidth())
        self.IDNV.setSizePolicy(sizePolicy)
        self.IDNV.setInputMask("")
        self.IDNV.setText("")
        self.IDNV.setObjectName("IDNV")
        self.gridLayout.addWidget(self.IDNV, 2, 1, 1, 5)
        self.StatusBox = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusBox.sizePolicy().hasHeightForWidth())
        self.StatusBox.setSizePolicy(sizePolicy)
        self.StatusBox.setReadOnly(True)
        self.StatusBox.setObjectName("StatusBox")
        self.gridLayout.addWidget(self.StatusBox, 5, 2, 1, 4)
        self.PhongBan = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PhongBan.sizePolicy().hasHeightForWidth())
        self.PhongBan.setSizePolicy(sizePolicy)
        self.PhongBan.setText("")
        self.PhongBan.setObjectName("PhongBan")
        self.gridLayout.addWidget(self.PhongBan, 1, 4, 1, 1)
        self.treeView = QtWidgets.QTreeView(parent=self.gridLayoutWidget)
        self.treeView.setObjectName("treeView")
        self.gridLayout.addWidget(self.treeView, 0, 1, 1, 5)
        self.SuaLuongNV = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuaLuongNV.sizePolicy().hasHeightForWidth())
        self.SuaLuongNV.setSizePolicy(sizePolicy)
        self.SuaLuongNV.setObjectName("SuaLuongNV")
        self.gridLayout.addWidget(self.SuaLuongNV, 3, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.Save = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save.sizePolicy().hasHeightForWidth())
        self.Save.setSizePolicy(sizePolicy)
        self.Save.setObjectName("Save")
        self.gridLayout.addWidget(self.Save, 6, 2, 1, 2)
        self.Exit = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Exit.sizePolicy().hasHeightForWidth())
        self.Exit.setSizePolicy(sizePolicy)
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 6, 4, 1, 2)

        self.retranslateUi(QLNV)
        QtCore.QMetaObject.connectSlotsByName(QLNV)

    def retranslateUi(self, QLNV):
        _translate = QtCore.QCoreApplication.translate
        QLNV.setWindowTitle(_translate("QLNV", "Dialog"))
        self.Status.setText(_translate("QLNV", "Status"))
        self.TenNV.setPlaceholderText(_translate("QLNV", "Tên NV"))
        self.LuongNV.setPlaceholderText(_translate("QLNV", "Lương NV"))
        self.ThemNV.setText(_translate("QLNV", "Thêm Nhân Viên"))
        self.XoaNV.setText(_translate("QLNV", "Xóa Nhân Viên"))
        self.ThongTinNV.setText(_translate("QLNV", "Chi Tiết Nhân Viên"))
        self.IDNV.setPlaceholderText(_translate("QLNV", "ID Nhân Viên"))
        self.PhongBan.setPlaceholderText(_translate("QLNV", "Phòng Ban"))
        self.SuaLuongNV.setText(_translate("QLNV", "Tăng Lương"))
        self.lineEdit.setPlaceholderText(_translate("QLNV", "Lương Tăng"))
        self.Save.setText(_translate("QLNV", "Save"))
        self.Exit.setText(_translate("QLNV", "Exit"))


        self.SuaLuongNV.clicked.connect(lambda: self.update_salary_NV())
        self.XoaNV.clicked.connect(lambda: self.delete_NV())
        self.ThemNV.clicked.connect(lambda: self.add_NV())
        self.Save.clicked.connect(lambda: self.save_file())
        self.ThongTinNV.clicked.connect(lambda: self.display_NV())
        self.Exit.clicked.connect(QLNV.close)

    def add_NV(self):
        ten = self.TenNV.text().strip()
        luong = self.LuongNV.text().strip()
        phongban = self.PhongBan.text().strip()
        id = self.PhongBan.text().strip()

        if ten == "" or luong == "" or phongban == "" or id == "":
            if ten == "":
                self.StatusBox.setText("Tên không được để trống")
            elif luong == "":
                self.StatusBox.setText("Lương không được để trống")
            elif phongban == "":
                self.StatusBox.setText("Phòng ban không được để trống")
            elif id == "":
                self.StatusBox.setText("ID không được để trống")
        else:
            employee = Employee(ten, luong, id, phongban)
            self.manager.add_NV(employee)
            self.StatusBox.setText("Thêm thành công")

        return
    
    def delete_NV(self):
        id = self.IDNV.text().strip()

        if id == "":
            self.StatusBox.setText("ID Không được để trống")
            return
        else:
            self.manager.delete_NV(id)
            self.StatusBox.setText("Xóa thành công")

    def save_file(self):
        self.StatusBox.setText("Đã lưu file")

    def update_salary_NV(self):
        id = self.IDNV.text().strip()
        luong = self.lineEdit.text().strip()

        if id == "" or luong == "":
            if id == "":
                self.StatusBox.setText("ID không được để trống")
            elif luong == "":
                self.StatusBox.setText("Lương không được để trống")
        else:
            self.manager.update_salary_NV(id, luong)
            self.StatusBox.setText("Tăng lương thành công")
    
    def display_NV(self):
        id = self.IDNV.text().strip()

        if id == "":
            self.StatusBox.setText("ID không được để trống")
        else:
            employee = self.manager.find_NV(id)
            if(employee == None):
                self.StatusBox.setText("Không tìm thấy nhân viên")
            else:
                self.StatusBox.setText(str(employee))
    
    def display_all_NV(self):
        dataNV = self.manager.load_NV()
        employees = ""
        for employee in dataNV:
            employees += str(employee) + "\n"

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    QLNV = QtWidgets.QDialog()
    ui = Ui_QLNV(manager=Manager())
    ui.setupUi(QLNV)
    QLNV.show()
    ui.display_all_NV()
    sys.exit(app.exec())